const chatMembers = [
    {
        name: "Dianne Russel",
        gender: "girl",
        imageSrc: "https://avatar.iran.liara.run/public/girl",
        microphoneEnabled: true,
        videoEnabled: false,
    },
    {
        name: "Guy Hawkins",
        gender: "boy",
        imageSrc: "https://avatar.iran.liara.run/public/boy",
        microphoneEnabled: false,
        videoEnabled: true,
    },
    {
        name: "Kathryn Murphy",
        gender: "girl",
        imageSrc: "https://avatar.iran.liara.run/public/girl",
        microphoneEnabled: true,
        videoEnabled: true,
    },
    {
        name: "Scroll Checker",
        username: "Scroll Checker",
        imageSrc: "https://avatar.iran.liara.run/username?username=Scroll+Checker",
        microphoneEnabled: false,
        videoEnabled: false,
    },
    {
        name: "Scroll Checker2",
        username: "Scroll Checker2",
        imageSrc: "https://avatar.iran.liara.run/username?username=Scroll+Checker2",
        microphoneEnabled: true,
        videoEnabled: false,
    },
    {
        name: "Alice Johnson",
        gender: "girl",
        imageSrc: "https://avatar.iran.liara.run/public/girl",
        microphoneEnabled: true,
        videoEnabled: true,
    },
    {
        name: "Bob Smith",
        gender: "boy",
        imageSrc: "https://avatar.iran.liara.run/public/boy",
        microphoneEnabled: false,
        videoEnabled: true,
    },
    {
        name: "Clara Lee",
        gender: "girl",
        imageSrc: "https://avatar.iran.liara.run/public/girl",
        microphoneEnabled: true,
        videoEnabled: false,
    },
    {
        name: "David Brown",
        gender: "boy",
        imageSrc: "https://avatar.iran.liara.run/public/boy",
        microphoneEnabled: false,
        videoEnabled: false,
    },
    {
        name: "Eve Thompson",
        gender: "girl",
        imageSrc: "https://avatar.iran.liara.run/public/girl",
        microphoneEnabled: true,
        videoEnabled: true,
    },
    {
        name: "Frank Williams",
        gender: "boy",
        imageSrc: "https://avatar.iran.liara.run/public/boy",
        microphoneEnabled: true,
        videoEnabled: false,
    },
    {
        name: "Grace Taylor",
        gender: "girl",
        imageSrc: "https://avatar.iran.liara.run/public/girl",
        microphoneEnabled: false,
        videoEnabled: true,
    },
    {
        name: "Hank Miller",
        gender: "boy",
        imageSrc: "https://avatar.iran.liara.run/public/boy",
        microphoneEnabled: true,
        videoEnabled: true,
    },
    {
        name: "Ivy Martinez",
        gender: "girl",
        imageSrc: "https://avatar.iran.liara.run/public/girl",
        microphoneEnabled: false,
        videoEnabled: false,
    },
    {
        name: "Jack Wilson",
        gender: "boy",
        imageSrc: "https://avatar.iran.liara.run/public/boy",
        microphoneEnabled: true,
        videoEnabled: false,
    },
    {
        name: "Lily Davis",
        gender: "girl",
        imageSrc: "https://avatar.iran.liara.run/public/girl",
        microphoneEnabled: true,
        videoEnabled: true,
    },
    {
        name: "Mark Garcia",
        gender: "boy",
        imageSrc: "https://avatar.iran.liara.run/public/boy",
        microphoneEnabled: false,
        videoEnabled: true,
    },
    {
        name: "Nina Hernandez",
        gender: "girl",
        imageSrc: "https://avatar.iran.liara.run/public/girl",
        microphoneEnabled: true,
        videoEnabled: false,
    },
    {
        name: "Oscar Lopez",
        gender: "boy",
        imageSrc: "https://avatar.iran.liara.run/public/boy",
        microphoneEnabled: true,
        videoEnabled: false,
    },
    {
        name: "Penny Gonzalez",
        gender: "girl",
        imageSrc: "https://avatar.iran.liara.run/public/girl",
        microphoneEnabled: false,
        videoEnabled: true,
    },
];


export default chatMembers;